version: '2'

services:
  node:
    image: node:9-alpine
    working_dir: /home/node/app
    volumes:
      - '.:/home/node/app/'
      - './sample-config.json:/home/node/app/server/config/config.json:ro'
  mongo:
    image: mongo
